"""Rotated surface code: lattice, syndrome-extraction schedule, decoding.

STATUS
------
**Verified against ``stim``, at d = 3, 5, 7 and 9:**

* the **lattice** -- data sites, ancilla sites, and every X/Z role assignment
  match the reference layout exactly;
* the **CNOT layer rule** reproduces the reference circuit gate for gate, in
  every layer, for every ancilla, at d = 3, 5, 7, 9 and 11.

Both are re-derived from ``stim`` by the test suite when it is installed, so
drift fails loudly.  ``stim`` is a development-time oracle, not a dependency.

**Bounded, not general.**  ``VERIFIED_SITES`` pins the layout for the four
distances above, and a distance without a verified layout is refused rather
than generated by a formula nobody has checked.  That is not laziness: five
attempts to *derive* the boundary rule produced lattices with the correct
*counts* and the wrong *sites*, which passes a qubit-count test and is therefore
the worst available failure mode.  Pinning verified data is the honest option.

**The decoder is exact within a bound.**  :class:`MWPMDecoder` enumerates perfect
matchings, so it is exact but factorial in the detection-event count; it raises
rather than silently approximating when the instance is too large.
:func:`greedy_match` remains available for larger instances and is honestly
labelled as worse.

The layer rule
--------------
Each ancilla has up to four data neighbours at offsets ``(±1, ±1)``.  The CNOT
layer in which each is visited is fixed by the offset::

    X-type (CNOT controls):   (1,1) -> (-1,1) -> (1,-1) -> (-1,-1)
    Z-type (CNOT targets):    (1,1) -> (1,-1) -> (-1,1) -> (-1,-1)

An ancilla has no gate in a layer whose offset does not exist for it, which
is how a weight-2 boundary check ends up using layers 2 and 3 rather than 0 and
1.  Getting that wrong -- consuming slots in order of *available* neighbours --
displaced the boundary checks and mismatched the schedule.  The two orders are
perpendicular in the sense that matters: a hook residual cannot run parallel to
the logical operator whose distance it could shorten.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

try:  # optional: only the DEM-derived graph and noisy sampling need it
    import stim

    HAVE_STIM = True
except ImportError:  # pragma: no cover - exercised by the skip path
    stim = None
    HAVE_STIM = False

#: Offset -> layer, per ancilla type.  **The index in the tuple is the layer.**
X_LAYERS: tuple[tuple[int, int], ...] = ((1, 1), (-1, 1), (1, -1), (-1, -1))
Z_LAYERS: tuple[tuple[int, int], ...] = ((1, 1), (1, -1), (-1, 1), (-1, -1))

#: All four neighbour offsets, for enumerating a check's support.
NEIGHBOUR_OFFSETS: tuple[tuple[int, int], ...] = ((1, 1), (1, -1), (-1, 1), (-1, -1))

N_LAYERS = 4

#: Verified ancilla placement, as ``{distance: ((x, y, kind), ...)}``. Taken from
#: ``stim``'s generated ``rotated_memory_z`` layout rather than inferred, because every
#: formula tried for the boundary rule gave a lattice whose qubit counts were right and
#: whose sites were wrong. Data qubits are at ``(2j+1, 2i+1)``, so an ancilla at
#: ``(x, y)`` has up to four data neighbours at offsets ``(±1, ±1)``; X ancillas are the
#: CNOT controls. ``tests/test_core/test_surface_code_schedule.py`` re-derives these
#: from ``stim`` and fails if they drift.
VERIFIED_SITES: dict[int, tuple[tuple[int, int, str], ...]] = {
    3: (
        (0, 4, "Z"), (2, 0, "X"), (2, 2, "Z"), (2, 4, "X"), (4, 2, "X"),
        (4, 4, "Z"), (4, 6, "X"), (6, 2, "Z"),
    ),
    5: (
        (0, 4, "Z"), (0, 8, "Z"), (2, 0, "X"), (2, 2, "Z"), (2, 4, "X"),
        (2, 6, "Z"), (2, 8, "X"), (4, 2, "X"), (4, 4, "Z"), (4, 6, "X"),
        (4, 8, "Z"), (4, 10, "X"), (6, 0, "X"), (6, 2, "Z"), (6, 4, "X"),
        (6, 6, "Z"), (6, 8, "X"), (8, 2, "X"), (8, 4, "Z"), (8, 6, "X"),
        (8, 8, "Z"), (8, 10, "X"), (10, 2, "Z"), (10, 6, "Z"),
    ),
    7: (
        (0, 4, "Z"), (0, 8, "Z"), (0, 12, "Z"), (2, 0, "X"), (2, 2, "Z"),
        (2, 4, "X"), (2, 6, "Z"), (2, 8, "X"), (2, 10, "Z"), (2, 12, "X"),
        (4, 2, "X"), (4, 4, "Z"), (4, 6, "X"), (4, 8, "Z"), (4, 10, "X"),
        (4, 12, "Z"), (4, 14, "X"), (6, 0, "X"), (6, 2, "Z"), (6, 4, "X"),
        (6, 6, "Z"), (6, 8, "X"), (6, 10, "Z"), (6, 12, "X"), (8, 2, "X"),
        (8, 4, "Z"), (8, 6, "X"), (8, 8, "Z"), (8, 10, "X"), (8, 12, "Z"),
        (8, 14, "X"), (10, 0, "X"), (10, 2, "Z"), (10, 4, "X"), (10, 6, "Z"),
        (10, 8, "X"), (10, 10, "Z"), (10, 12, "X"), (12, 2, "X"), (12, 4, "Z"),
        (12, 6, "X"), (12, 8, "Z"), (12, 10, "X"), (12, 12, "Z"), (12, 14, "X"),
        (14, 2, "Z"), (14, 6, "Z"), (14, 10, "Z"),
    ),
    9: (
        (0, 4, "Z"), (0, 8, "Z"), (0, 12, "Z"), (0, 16, "Z"), (2, 0, "X"),
        (2, 2, "Z"), (2, 4, "X"), (2, 6, "Z"), (2, 8, "X"), (2, 10, "Z"),
        (2, 12, "X"), (2, 14, "Z"), (2, 16, "X"), (4, 2, "X"), (4, 4, "Z"),
        (4, 6, "X"), (4, 8, "Z"), (4, 10, "X"), (4, 12, "Z"), (4, 14, "X"),
        (4, 16, "Z"), (4, 18, "X"), (6, 0, "X"), (6, 2, "Z"), (6, 4, "X"),
        (6, 6, "Z"), (6, 8, "X"), (6, 10, "Z"), (6, 12, "X"), (6, 14, "Z"),
        (6, 16, "X"), (8, 2, "X"), (8, 4, "Z"), (8, 6, "X"), (8, 8, "Z"),
        (8, 10, "X"), (8, 12, "Z"), (8, 14, "X"), (8, 16, "Z"), (8, 18, "X"),
        (10, 0, "X"), (10, 2, "Z"), (10, 4, "X"), (10, 6, "Z"), (10, 8, "X"),
        (10, 10, "Z"), (10, 12, "X"), (10, 14, "Z"), (10, 16, "X"),
        (12, 2, "X"), (12, 4, "Z"), (12, 6, "X"), (12, 8, "Z"), (12, 10, "X"),
        (12, 12, "Z"), (12, 14, "X"), (12, 16, "Z"), (12, 18, "X"),
        (14, 0, "X"), (14, 2, "Z"), (14, 4, "X"), (14, 6, "Z"), (14, 8, "X"),
        (14, 10, "Z"), (14, 12, "X"), (14, 14, "Z"), (14, 16, "X"),
        (16, 2, "X"), (16, 4, "Z"), (16, 6, "X"), (16, 8, "Z"), (16, 10, "X"),
        (16, 12, "Z"), (16, 14, "X"), (16, 16, "Z"), (16, 18, "X"),
        (18, 2, "Z"), (18, 6, "Z"), (18, 10, "Z"), (18, 14, "Z"),
    ),
}

#: Distances for which a verified layout is available.
SUPPORTED_DISTANCES: tuple[int, ...] = tuple(sorted(VERIFIED_SITES))


def layer_of(is_x: bool, offset: tuple[int, int]) -> int:
    """Which syndrome-extraction layer a given neighbour ``offset`` belongs to.

    The offset is measured **from the ancilla to the data qubit** as
    ``(dx, dy)``.  A ``ValueError`` means the offset is not a neighbour at all,
    which is a programming error rather than a runtime condition.

    This is the schedule rule on its own, independent of the lattice: it is what
    the cross-validation against ``stim`` exercises, so a wrong rule fails there
    even if :class:`RotatedSurfaceCode` builds something self-consistent.
    """
    table = X_LAYERS if is_x else Z_LAYERS
    try:
        return table.index(offset)
    except ValueError as exc:
        kind = "X" if is_x else "Z"
        raise ValueError(
            f"{offset} is not a neighbour offset for a {kind}-type ancilla"
        ) from exc


class SurfaceCodeError(ValueError):
    """Raised for an invalid surface code construction."""


@dataclass(frozen=True)
class Check:
    """One stabilizer measurement: an ancilla, its type, and its data support."""

    ancilla: int
    kind: str                     # "X" or "Z"
    x: int
    y: int
    support: tuple[int, ...]

    @property
    def weight(self) -> int:
        return len(self.support)

    @property
    def layers(self) -> tuple[tuple[int, int], ...]:
        """``(layer, data_qubit)`` pairs in CNOT order.

        The layer comes from the offset table, so a weight-2 boundary check
        keeps its gates in the same layers as everything else of its type.
        """
        offsets = X_LAYERS if self.kind == "X" else Z_LAYERS
        positions = {q: off for q, off in zip(self.support, self._offsets())}
        out = []
        for layer, offset in enumerate(offsets):
            for data, actual in positions.items():
                if actual == offset:
                    out.append((layer, data))
        return tuple(sorted(out))

    def _offsets(self) -> list[tuple[int, int]]:
        return self._cached_offsets

    # dataclass is frozen, so the offsets are attached at construction time
    _cached_offsets: tuple[tuple[int, int], ...] = ()


@dataclass
class RotatedSurfaceCode:
    """The rotated surface code at a given distance.

    Qubit numbering: data qubits are ``d*i + j`` for row ``i``, column ``j``; ancillas
    begin at ``d*d``.  That keeps data indices dense and small, which matters for
    the tableau simulator's memory.
    """

    distance: int
    checks: list[Check] = field(default_factory=list)
    data_coords: dict[int, tuple[int, int]] = field(default_factory=dict)
    ancilla_coords: dict[int, tuple[int, int]] = field(default_factory=dict)

    def __post_init__(self):
        if self.distance < 2:
            raise SurfaceCodeError(
                f"distance must be at least 2, got {self.distance}"
            )
        self._build()

    def _build(self) -> None:
        """Lay out the lattice from the **verified** site table.

        Not from a formula.  Five attempts to express the boundary rule as a
        formula each produced a lattice with the correct *counts* and the wrong
        *sites* -- which passes the qubit-count test and is therefore the worst
        available failure mode.  The sites are taken from the reference layout
        and pinned in :data:`VERIFIED_SITES`, and the test suite re-derives them
        from ``stim`` when it is available.

        Data qubits are ``d*i + j`` at ``(2j+1, 2i+1)``; ancillas are numbered from
        ``d*d`` in the table's order.
        """
        d = self.distance
        if d not in VERIFIED_SITES:
            raise SurfaceCodeError(
                f"no verified layout for distance {d}; available: "
                f"{list(SUPPORTED_DISTANCES)}. A distance without a verified "
                f"layout is refused rather than generated by a rule that has "
                f"not been checked."
            )

        for i in range(d):
            for j in range(d):
                self.data_coords[d * i + j] = (2 * j + 1, 2 * i + 1)
        coord_to_data = {xy: q for q, xy in self.data_coords.items()}

        next_ancilla = d * d
        for x, y, kind in VERIFIED_SITES[d]:
            support = []
            offsets = []
            for off in NEIGHBOUR_OFFSETS:
                pos = (x + off[0], y + off[1])
                if pos in coord_to_data:
                    support.append(coord_to_data[pos])
                    offsets.append(off)
            if len(support) < 2:
                raise SurfaceCodeError(
                    f"verified site ({x}, {y}) at d={d} has only "
                    f"{len(support)} data neighbours; the table is corrupt"
                )
            ordered = sorted(support)
            self.ancilla_coords[next_ancilla] = (x, y)
            self.checks.append(Check(
                ancilla=next_ancilla, kind=kind, x=x, y=y,
                support=tuple(ordered),
                _cached_offsets=tuple(
                    (self.data_coords[q][0] - x, self.data_coords[q][1] - y)
                    for q in ordered
                ),
            ))
            next_ancilla += 1

    # -- queries -----------------------------------------------------------

    @property
    def n_data(self) -> int:
        return self.distance * self.distance

    @property
    def n_ancilla(self) -> int:
        return len(self.checks)

    @property
    def n_qubits(self) -> int:
        return self.n_data + self.n_ancilla

    @property
    def x_checks(self) -> list[Check]:
        return [c for c in self.checks if c.kind == "X"]

    @property
    def z_checks(self) -> list[Check]:
        return [c for c in self.checks if c.kind == "Z"]

    def logical_z(self) -> list[int]:
        """A logical Z operator: every data qubit in the first row.

        Chosen to match the observable ``stim`` uses for ``rotated_memory_z``,
        so logical error rates are comparable.
        """
        d = self.distance
        return [d * 0 + j for j in range(d)]

    def logical_x(self) -> list[int]:
        """A logical X operator: every data qubit in the first column."""
        d = self.distance
        return [d * i + 0 for i in range(d)]

    def ancilla_support(self, ancilla: int) -> tuple[int, ...]:
        """The data qubits a given ancilla measures."""
        for check in self.checks:
            if check.ancilla == ancilla:
                return check.support
        raise SurfaceCodeError(f"no ancilla {ancilla} in the lattice")

    def cnot_layers(self) -> list[list[tuple[int, int]]]:
        """The four syndrome-extraction layers, as ``(control, target)`` pairs.

        X-type ancillas are controls; Z-type are targets.  The layer assignment
        comes from :attr:`Check.layers`, which is the verified rule.
        """
        layers: list[list[tuple[int, int]]] = [[] for _ in range(N_LAYERS)]
        for check in self.checks:
            for layer, data in check.layers:
                if check.kind == "X":
                    layers[layer].append((check.ancilla, data))
                else:
                    layers[layer].append((data, check.ancilla))
        return layers

    def verify_layers(self) -> dict:
        """Structural invariants a valid syndrome round must satisfy.

        Cheap checks that catch a mis-built lattice before it produces a
        plausible-looking but wrong error rate:

        * every data qubit is touched by exactly one gate per layer it appears in
        * no qubit is the target of two gates in the same layer
        * no ancilla appears twice in one layer
        """
        layers = self.cnot_layers()
        problems: list[str] = []
        for index, layer in enumerate(layers):
            controls = [c for c, _ in layer]
            targets = [t for _, t in layer]
            if len(set(controls)) != len(controls):
                problems.append(f"layer {index}: a qubit controls two gates")
            if len(set(targets)) != len(targets):
                problems.append(f"layer {index}: a qubit is target of two gates")
            overlap = set(controls) & set(targets)
            if overlap:
                problems.append(f"layer {index}: {sorted(overlap)} used twice")
        return {
            "distance": self.distance,
            "layers": [len(layer) for layer in layers],
            "problems": problems,
            "valid": not problems,
        }

    def summary(self) -> str:
        return (f"RotatedSurfaceCode(d={self.distance}): "
                f"{self.n_data} data + {self.n_ancilla} ancilla "
                f"= {self.n_qubits} qubits, "
                f"{len(self.x_checks)} X-checks, {len(self.z_checks)} Z-checks, "
                f"weights {sorted({c.weight for c in self.checks})}")


# Decoding: minimum-weight matching on the syndrome graph

@dataclass
class DecodeResult:
    """Outcome of one decoding pass."""

    corrections: list[int]
    residual: list[int]
    logical_flip: bool

    def describe(self) -> str:
        return (f"corrected {len(self.corrections)} qubits, "
                f"{len(self.residual)} unmatched, "
                f"logical flip: {self.logical_flip}")


def logical_operator_for(code: RotatedSurfaceCode, kind: str) -> list[int]:
    """Which logical operator a correction of this check type can flip.

    **This is the easy thing to get backwards, and getting it backwards silently
    inverts every logical error rate.**  An X-type stabilizer detects *Z* errors,
    and a Z-error chain crossing the code flips the **X** logical operator -- not
    the Z one.  So:

    * ``kind == "X"`` -> test against the **X** logical (a column);
    * ``kind == "Z"`` -> test against the **Z** logical (a row).

    The first version used the Z logical for X-checks, which scored an X-error
    that actually mattered as harmless and one that did not as a logical failure.
    Every logical error rate it produced would have been wrong in a way that
    still looks like a plausible number.
    """
    if kind == "X":
        return code.logical_x()
    if kind == "Z":
        return code.logical_z()
    raise SurfaceCodeError(f"kind must be 'X' or 'Z', got {kind!r}")


class SpaceTimeMatchingGraph:
    """The syndrome graph with a **time dimension**, one layer per round.

    Why a single-round graph cannot work
    ------------------------------------
    A measurement error flips one ancilla's *outcome* without flipping its
    neighbours'.  In a flat, single-round graph that event looks like an
    isolated detection event with nothing near it, so the decoder matches it to
    the nearest boundary -- a long, expensive correction -- or pairs it with an
    unrelated event.  Both are wrong.

    The fix is the standard one: replicate the check graph once per round, add a
    **vertical edge** between each ancilla's copies in consecutive rounds
    representing a measurement error, and connect the first and last layers to
    the boundaries.  A chain then runs through space *and* time, and a
    measurement error is a cheap one-edge correction instead of a misdiagnosis.

    Measured consequence of not doing this: at distance 5 the single-round
    clustered decoder disagreed with exact matching on 18 of 710 real syndromes,
    and the per-round logical error rate rose with distance at every noise level
    tested -- the above-threshold signature, produced by a decoder that could not
    represent the dominant error mechanism.

    Nodes are ``(round, ancilla)``.  Boundaries are per-layer, so a chain can
    terminate at the code edge in any round.
    """

    def __init__(self, code, kind: str, rounds: int):
        if kind not in ("X", "Z"):
            raise SurfaceCodeError(f"kind must be 'X' or 'Z', got {kind!r}")
        if rounds < 1:
            raise ValueError("rounds must be at least 1")
        self.kind = kind
        self.rounds = rounds
        self.code = code

        single = matching_graph(code, kind)
        self.ancillas = sorted(single["nodes"])
        self._single_edges = single["edges"]
        self._single_boundaries = sorted(single["boundary_nodes"])

        # Vertical (time) edges: a measurement error on one ancilla.
        self.vertical: set[tuple[tuple[int, int], tuple[int, int]]] = set()
        for r in range(rounds - 1):
            for ancilla in self.ancillas:
                self.vertical.add(((r, ancilla), (r + 1, ancilla)))

        # Space edges: the single-round graph, replicated into every layer.
        self.horizontal: dict[tuple[tuple[int, int], tuple[int, int]], int] = {}
        for r in range(rounds):
            for (a, b), data in single["edges"].items():
                if a > 0 and b > 0:
                    self.horizontal[((r, a), (r, b))] = data

        # Boundaries per layer, plus the two end caps that terminate a chain at
        # the start or end of the experiment.
        self.boundaries: set[tuple[int, int]] = set()
        self.boundary_single: dict[tuple[int, int], int] = {}
        for r in range(rounds):
            for index, bound in enumerate(self._single_boundaries):
                key = (r, -(index + 1))
                self.boundaries.add(key)
                # which boundary node it corresponds to in the single graph
                self.boundary_single[key] = bound
        self.cap_start = (-1, 0)
        self.cap_end = (rounds, 0)
        self.boundaries.add(self.cap_start)
        self.boundaries.add(self.cap_end)
        self.boundary_single[self.cap_start] = self.cap_start
        self.boundary_single[self.cap_end] = self.cap_end

    def edges(self) -> dict:
        """Every edge, as ``{(node_a, node_b): data_qubit_or_None}``.

        A ``None`` payload marks a time or boundary edge: it costs a correction
        slot but does not name a data qubit, because a measurement error is not a
        data error.
        """
        out: dict[tuple, int | None] = {}
        for (a, b), data in self.horizontal.items():
            out[self._key(a, b)] = data
        for a, b in self.vertical:
            out[self._key(a, b)] = None

        # Each layered boundary connects to the ancillas the single-round graph matched
        # to the corresponding boundary.
        for key, single_bound in self.boundary_single.items():
            if key in (self.cap_start, self.cap_end):
                continue
            round_index = key[0]
            for (a, b), data in self._single_edges.items():
                if a == single_bound or b == single_bound:
                    ancilla = b if a == single_bound else a
                    if ancilla > 0:
                        out[self._key(key, (round_index, ancilla))] = data

        # Boundaries are chained through time and the two ends of the experiment are
        # closed off by cap nodes; without this a layered boundary is unreachable.
        layered = [k for k in self.boundaries
                   if k not in (self.cap_start, self.cap_end)]
        by_index: dict[int, list[int]] = {}
        for key in layered:
            by_index.setdefault(-key[1], []).append(key[0])
        for index, rounds_used in by_index.items():
            ordered = sorted(rounds_used)
            for a, b in zip(ordered, ordered[1:]):
                out[self._key((a, -(index)), (b, -(index)))] = None
            # End caps anchor the first and last occurrence of this boundary.
            out[self._key(self.cap_start, (ordered[0], -(index)))] = None
            out[self._key((ordered[-1], -(index)), self.cap_end)] = None
        return out

    @staticmethod
    def _key(a, b):
        return (a, b) if a <= b else (b, a)

    @property
    def nodes(self) -> list:
        return [(r, a) for r in range(self.rounds) for a in self.ancillas]

    def boundary_nodes(self) -> list:
        return sorted(self.boundaries)


def decode_space_time(code, events_by_round: dict, kind: str, rounds: int,
                      max_events: int = 14) -> DecodeResult:
    """Exact space-time decoding by exhaustive matching.  Small instances only.

    Kept as the reference for :func:`decode_space_time_greedy`: exact, but
    factorial in the event count.  Use the greedy decoder for anything a real
    experiment would produce.
    """
    graph = SpaceTimeMatchingGraph(code, kind, rounds)
    all_edges = graph.edges()
    adjacency: dict = {}
    for (a, b), data in all_edges.items():
        adjacency.setdefault(a, []).append((b, data))
        adjacency.setdefault(b, []).append((a, data))

    events = {(r, ancilla) for r, fired in events_by_round.items()
              for ancilla in fired}
    events = {e for e in events if e in adjacency}
    if not events:
        return DecodeResult(corrections=[], residual=[], logical_flip=False)
    if len(events) > max_events:
        raise SurfaceCodeError(
            f"{len(events)} space-time events exceeds the exact limit of "
            f"{max_events}; use decode_space_time_greedy"
        )

    return _match_events(code, kind, adjacency,
                         [b for b in graph.boundary_nodes() if b in adjacency],
                         events)


def decode_space_time_greedy(code, events_by_round: dict, kind: str,
                             rounds: int, *, boundary_penalty: int = 0,
                             max_events: int = 4000) -> DecodeResult:
    """Scalable space-time decoding: greedy pairing over the layered graph.

    Why this is the one that matters
    --------------------------------
    Exact matching enumerates perfect matchings, and a distance-5 experiment at a
    realistic error rate produces of order ten detection events *per round*
    across five rounds, plus the per-layer boundary nodes.  The enumeration is
    hopeless there, and a decoder that cannot run is not a decoder: it means no
    logical error rate can be measured, which is the state this module was in.

    The algorithm is greedy nearest-neighbour pairing in the space-time graph.
    Each event is connected to its nearest remaining partner (another event, or
    the nearest boundary) by the shortest path, and every edge on that path
    contributes one correction.  It is an approximation: greedy pairing is
    not minimum-weight, and the gap is why a threshold is always quoted with the
    decoder named beside it.  :func:`decode_space_time` provides the exact answer
    on instances both can handle, so the gap is measurable rather than assumed.

    The time dimension is what makes this work at all.  A measurement error is a
    single vertical edge, so the decoder repairs it for the cost of one edge
    instead of misdiagnosing it as an isolated event and matching it across the
    code.
    """
    graph = SpaceTimeMatchingGraph(code, kind, rounds)
    all_edges = graph.edges()
    adjacency: dict = {}
    for (a, b), data in all_edges.items():
        adjacency.setdefault(a, []).append((b, data))
        adjacency.setdefault(b, []).append((a, data))

    events = {(r, ancilla) for r, fired in events_by_round.items()
              for ancilla in fired}
    orphaned = sorted(e for e in events if e not in adjacency)
    live = sorted(e for e in events if e in adjacency)
    if not live:
        return DecodeResult(corrections=[], residual=orphaned,
                            logical_flip=False)
    if len(live) > max_events:
        raise SurfaceCodeError(
            f"{len(live)} events exceeds the configured maximum of {max_events}"
        )

    boundaries = [b for b in graph.boundary_nodes() if b in adjacency]
    paths = {e: shortest_paths(adjacency, e) for e in live}

    remaining = list(live)
    corrections: set[int] = set()
    unmatched: list = []
    while remaining:
        event = remaining.pop(0)
        best_cost: float | None = None
        best_path: list | None = None
        best_partner = None

        for other in remaining:
            found = paths[event].get(other)
            if found is not None and (best_cost is None or found[0] < best_cost):
                best_cost, best_path, best_partner = found[0], found[1], other

        boundary_best: tuple[float, list] | None = None
        for bound in boundaries:
            found = paths[event].get(bound)
            if found is None:
                continue
            cost = found[0] + boundary_penalty
            if boundary_best is None or cost < boundary_best[0]:
                boundary_best = (cost, found[1])

        if best_cost is not None and (boundary_best is None
                                      or best_cost <= boundary_best[0]):
            corrections.update(p for p in (best_path or []) if p is not None)
            if best_partner in remaining:
                remaining.remove(best_partner)
        elif boundary_best is not None:
            corrections.update(p for p in boundary_best[1] if p is not None)
        else:
            unmatched.append(event)

    logical = set(logical_operator_for(code, kind))
    flips = len(logical & corrections) % 2 == 1
    return DecodeResult(corrections=sorted(corrections),
                        residual=orphaned + unmatched, logical_flip=flips)


def _match_events(code, kind: str, adjacency: dict, boundaries: list,
                  events) -> DecodeResult:
    """Shared exhaustive matcher, used by the exact space-time decoder."""
    from itertools import combinations

    event_list = sorted(events)
    distances = {e: shortest_paths(adjacency, e) for e in event_list}
    for a in boundaries:
        distances.setdefault(a, {})
    for a in boundaries:
        for b in boundaries:
            if a != b:
                distances[a][b] = (0, [])

    def path_between(a, b):
        found = distances.get(a, {}).get(b)
        if found is None:
            found = distances.get(b, {}).get(a)
        return found

    best: tuple[int, set[int]] | None = None
    for count in range(0, min(len(event_list), 6) + 1):
        for subset in combinations(event_list, count):
            interior = [e for e in event_list if e not in subset]
            if len(interior) % 2:
                continue
            total = 0
            chosen: set[int] = set()
            ok = True
            for e in subset:
                options = [path_between(e, b) for b in boundaries]
                options = [o for o in options if o is not None]
                if not options:
                    ok = False
                    break
                cost, path = min(options, key=lambda t: t[0])
                total += cost
                chosen.update(p for p in path if p is not None)
            if not ok:
                continue
            for matching in _perfect_matchings(tuple(interior)):
                cost = total
                candidate = set(chosen)
                feasible = True
                for a, b in matching:
                    found = path_between(a, b)
                    if found is None:
                        feasible = False
                        break
                    cost += found[0]
                    candidate.update(p for p in found[1] if p is not None)
                if feasible and (best is None or cost < best[0]):
                    best = (cost, candidate)

    if best is None:
        return DecodeResult(corrections=[], residual=sorted(events),
                            logical_flip=False)
    logical = set(logical_operator_for(code, kind))
    flips = len(logical & best[1]) % 2 == 1
    return DecodeResult(corrections=sorted(best[1]), residual=[],
                        logical_flip=flips)


def _noisy_memory_circuit(distance: int, rounds: int, noise: float):
    """A depolarising-gate memory circuit, used only to obtain the DEM.

    Deliberately independent of ``quantumnet.core.logical`` to avoid a circular
    import; the DEM's *topology* does not depend on the noise magnitude, only on
    which mechanisms are present.
    """
    if not HAVE_STIM:
        raise SurfaceCodeError("needs `pip install stim`")
    return stim.Circuit.generated(
        "surface_code:rotated_memory_z",
        distance=distance,
        rounds=rounds,
        after_clifford_depolarization=noise,
    )


def dem_matching_graph(distance: int, kind: str, rounds: int | None = None):
    """Matching graph taken from ``stim``'s detector error model.

    Why this replaces the hand-built graph
    --------------------------------------
    The space-time geometry was hand-reconstructed four times and was wrong every
    time, in a way that passed every structural check: connected, every ancilla
    reaches a boundary, every single error yields a length-one correction.  The
    count is what exposed it.  At d=3 the DEM contains 82 graphlike error
    mechanisms; the hand-built graph had 17, with none of its edges spurious.
    It was missing 79% of the graph, mostly the *diagonal* space-time edges where
    a data error flips two neighbouring ancillas measured at different times, and
    the deficit grew with distance, which is why the logical error rate refused to
    scale.

    The DEM is derived by ``stim`` from the circuit actually being sampled, so it
    is the instrument's own model of its own circuit.  That is a categorically
    better position than any reading of the geometry, and it is why this
    supersedes rather than supplements the hand-built version.

    Returns ``(adjacency, detector_to_node)``, where ``adjacency`` maps a node to
    ``[(neighbour, data_qubit_or_None)]``.  A ``None`` payload is a time or
    boundary edge: it costs a correction slot but names no data qubit, because a
    measurement error is not a data error.
    """
    if not HAVE_STIM:
        raise SurfaceCodeError(
            "the detector-error-model graph needs `pip install stim`"
        )
    rounds = distance if rounds is None else rounds
    circuit = _noisy_memory_circuit(distance, rounds, 0.001)
    dem = circuit.detector_error_model(decompose_errors=True)

    code = RotatedSurfaceCode(distance)
    coordinate_of = {code.ancilla_coords[c.ancilla]: c.ancilla for c in code.checks
                     if c.kind == kind}
    if not coordinate_of:
        raise SurfaceCodeError(f"no {kind}-type checks in the lattice")

    # DEM detectors carry the ancilla coordinate and the measurement time.
    detector_coords: dict[int, tuple[int, int, int]] = {}
    index = 0
    for inst in dem.flattened():
        if inst.type == "detector":
            args = list(inst.args_copy())
            if len(args) >= 3:
                detector_coords[index] = (int(args[0]), int(args[1]),
                                          int(args[2]))
            index += 1

    times = sorted({t for (_, _, t) in detector_coords.values()})
    round_of = {t: i for i, t in enumerate(times)}

    to_node: dict[int, tuple[int, int]] = {}
    for det, (x, y, t) in detector_coords.items():
        ancilla = coordinate_of.get((x, y))
        if ancilla is not None:
            to_node[det] = (round_of[t], ancilla)

    adjacency: dict[tuple[int, int], list] = {}
    seen_edges: set[tuple] = set()
    skipped = 0

    def add_edge(a, b, data) -> None:
        """Add one undirected edge, ignoring a duplicate of the same pair.

        Many DEM components describe the same pair of detectors -- a data error
        and a measurement error can both connect them, with the same payload for
        our purposes.  Appending blindly inflates the adjacency and makes the
        edge count exceed the component count, which is both wrong and a useful
        signal that something is over-counting.
        """
        # Nodes are either ``(round, ancilla)`` tuples or the boundary pseudo-node, so
        # compare by a normalised sort key: the two types are not orderable.
        key = (a, b) if _node_key(a) <= _node_key(b) else (b, a)
        if key in seen_edges:
            return
        seen_edges.add(key)
        adjacency.setdefault(a, []).append((b, data))
        adjacency.setdefault(b, []).append((a, data))

    for inst in dem.flattened():
        if inst.type != "error":
            continue
        # A DEM mechanism is a set of separated components, not a detector list: stim
        # writes ``error(p) D1 D5 ^ D4`` and ``^`` separates them, each graphlike under
        # ``decompose_errors=True`` (verified at d=3, 5 and 7, where 0 of 556, 3706 and
        # 11830 components exceeded two detectors). Counting detectors across the whole
        # mechanism instead discards 147 of 286 mechanisms at d=3.
        components = _dem_components(inst)
        for component in components:
            if len(component) == 2:
                a, b = to_node.get(component[0]), to_node.get(component[1])
                if a is None or b is None or a == b:
                    skipped += 1
                    continue
                add_edge(a, b, dem_error_data_qubit(a, b, code))
            elif len(component) == 1:
                node = to_node.get(component[0])
                if node is None:
                    skipped += 1
                    continue
                # A single-detector component is a chain ending at the code edge.
                add_edge(node, _DEM_BOUNDARY, None)
            else:
                # Should not happen with decompose_errors=True; counted rather than
                # silently dropped so a future stim change is visible.
                skipped += 1
    return adjacency, to_node


#: Pseudo-node representing the code edge in a DEM-derived graph.
_DEM_BOUNDARY = ("DEM_BOUNDARY",)


def _node_key(node) -> tuple:
    """Total order over mixed graph nodes, for canonical edge keys.

    Detector nodes are ``(round, ancilla)`` integer pairs; the boundary is a
    one-element string tuple.  Comparing them directly raises, so both are
    normalised to ``(kind, ...)`` with the boundary sorted last.
    """
    if node == _DEM_BOUNDARY:
        return (1, 0, 0)
    return (0, node[0], node[1])


def _dem_components(instruction) -> list[list[int]]:
    """Split a DEM error instruction into its ``^``-separated components.

    Each component is a list of detector ids.  ``stim`` separates them with
    ``target.is_separator()``; treating the instruction's targets as one flat
    list is what made a two-component graphlike error look like a four-detector
    hyperedge.
    """
    components: list[list[int]] = []
    current: list[int] = []
    for target in instruction.targets_copy():
        if target.is_separator():
            if current:
                components.append(current)
            current = []
        elif target.is_relative_detector_id():
            current.append(target.val)
    if current:
        components.append(current)
    return components


def dem_error_data_qubit(a, b, code) -> int | None:
    """Best-effort data qubit for a DEM edge, or ``None`` for a time edge.

    Two ancillas in the same round sharing a data qubit -> that qubit.  Two
    occurrences of the same ancilla in consecutive rounds -> a measurement error,
    so no data qubit.  Anything else is a diagonal space-time edge, where naming a
    single data qubit is not meaningful; ``None`` is the honest answer and the
    decoder treats it as a costed edge without a physical correction label.
    """
    (r1, a1), (r2, a2) = a, b
    if r1 == r2:
        shared = set(code.ancilla_support(a1)) & set(code.ancilla_support(a2))
        if len(shared) == 1:
            return shared.pop()
    return None


def syndrome_graph(code: RotatedSurfaceCode, kind: str) -> dict:
    """Build the decoding graph for one check type.

    Nodes are the ancillas of that type plus the two **boundary nodes** that
    represent a chain ending at the code boundary -- without them a detection
    event near an edge has nothing to match to, and the decoder cannot tell a
    chain that terminates on the boundary from one that crosses the code.

    Edges connect ancillas that share exactly one data qubit, because a single
    data error flips exactly those.  Those edges are the matchable units.
    """
    if kind not in ("X", "Z"):
        raise SurfaceCodeError(f"kind must be 'X' or 'Z', got {kind!r}")
    checks = [c for c in code.checks if c.kind == kind]

    # data qubit -> checks that contain it
    by_data: dict[int, list[int]] = {}
    for check in checks:
        for data in check.support:
            by_data.setdefault(data, []).append(check.ancilla)

    edges: dict[tuple[int, int], int] = {}
    for data, ancillas in by_data.items():
        if len(ancillas) == 2:
            a, b = sorted(ancillas)
            edges[(a, b)] = data
        elif len(ancillas) == 1:
            # A data qubit in exactly one check of this type: an error there flips one
            # ancilla, and must be matchable to the boundary.
            edges[(ancillas[0], -1 if kind == "X" else -2)] = data

    return {
        "kind": kind,
        "ancillas": [c.ancilla for c in checks],
        "edges": edges,
        "boundary_x": -1,
        "boundary_z": -2,
    }


def greedy_match(syndrome: set[int], edges: dict[tuple[int, int], int],
                 boundary: tuple[int, ...]) -> tuple[list[int], list[int]]:
    """Greedy nearest-neighbour pairing of detection events.

    Not minimum-weight matching.  A deliberate choice for a dependency-free
    implementation: greedy matching is a few lines of plain Python, needs no
    solver, and is *known* to be worse than MWPM rather than silently claimed to
    be equal to it.  Where a threshold is quoted, the decoder is named alongside
    it -- a threshold is a property of the decoder as much as of the code.

    Returns ``(data_qubits_to_flip, unmatched_nodes)``.
    """
    # Simple BFS distances over the adjacency implied by the edges.
    adjacency: dict[int, dict[int, int]] = {}
    for (a, b), data in edges.items():
        adjacency.setdefault(a, {})[b] = data
        adjacency.setdefault(b, {})[a] = data

    def distance(src: int, dst: int) -> tuple[int, list[int]] | None:
        if src == dst:
            return (0, [])
        seen = {src}
        queue = [(src, 0, [])]
        while queue:
            node, dist, path = queue.pop(0)
            for nxt, data in adjacency.get(node, {}).items():
                if nxt in seen:
                    continue
                new_path = path + [data]
                if nxt == dst:
                    return (dist + 1, new_path)
                seen.add(nxt)
                queue.append((nxt, dist + 1, new_path))
        return None

    remaining = sorted(syndrome)
    corrections: list[int] = []
    unmatched: list[int] = []

    while remaining:
        node = remaining.pop(0)
        best = None
        for other in remaining:
            found = distance(node, other)
            if found is not None and (best is None or found[0] < best[1][0]):
                best = (other, found)
        # Consider the boundary as an alternative match.
        for bound in boundary:
            found = distance(node, bound)
            if found is not None and (best is None or found[0] < best[1][0]):
                best = (bound, found)

        if best is None:
            unmatched.append(node)
            continue
        partner, (_, path) = best
        corrections.extend(path)
        if partner in remaining:
            remaining.remove(partner)
    return corrections, unmatched


def matching_graph(code: RotatedSurfaceCode, kind: str) -> dict:
    """The decoding graph, with boundary nodes included.

    Boundary nodes are what let a chain terminate at the code edge instead of
    having to pair with another detection event.  Without them an odd number of
    events near an edge has no valid matching at all, and a decoder that
    silently drops the leftover reports a correction it cannot justify.

    Each boundary node represents *one edge* of the code, not one whole side, so
    a chain reaching the wrong edge does not match for free -- which is what
    keeps the boundary from absorbing real errors.

    Returns ``nodes``, ``edges`` keyed by an unordered pair, and the two
    boundary-node families.
    """
    if kind not in ("X", "Z"):
        raise SurfaceCodeError(f"kind must be 'X' or 'Z', got {kind!r}")
    checks = [c for c in code.checks if c.kind == kind]

    by_data: dict[int, list[int]] = {}
    for check in checks:
        for data in check.support:
            by_data.setdefault(data, []).append(check.ancilla)

    edges: dict[tuple[int, int], int] = {}
    nodes: set[int] = {c.ancilla for c in checks}
    boundary_nodes: set[int] = set()
    next_boundary = -1

    for data, ancillas in by_data.items():
        if len(ancillas) == 2:
            a, b = sorted(ancillas)
            edges[(a, b)] = data
        elif len(ancillas) == 1:
            # A data qubit monitored by one check of this type: an error there flips
            # that check and is indistinguishable from one at the edge, so it must be
            # matchable to a boundary node.
            node = ancillas[0]
            boundary = next_boundary
            next_boundary -= 1
            boundary_nodes.add(boundary)
            edges[(min(node, boundary), max(node, boundary))] = data

    # Boundary nodes are mutually connected at zero cost, so a chain may pass along an
    # edge without being charged for it.
    return {
        "kind": kind,
        "nodes": nodes,
        "boundary_nodes": boundary_nodes,
        "edges": edges,
        "next_boundary": next_boundary,
    }


def decode(code: RotatedSurfaceCode, syndrome: set[int],
           kind: str) -> DecodeResult:
    """Decode one syndrome with greedy nearest-neighbour pairing."""
    graph = syndrome_graph(code, kind)
    boundary = (graph["boundary_x"], graph["boundary_z"])
    # Only nodes present in the graph's edges can be matched.
    corrections, unmatched = greedy_match(syndrome, graph["edges"], boundary)

    logical = set(logical_operator_for(code, kind))
    flips_logical = (len(logical & set(corrections)) % 2 == 1)
    return DecodeResult(corrections=sorted(set(corrections)),
                        residual=unmatched,
                        logical_flip=flips_logical)


# Minimum-weight perfect matching


def _adjacency(edges: dict[tuple[int, int], int]) -> dict[int, list[tuple[int, int]]]:
    """``{node: [(neighbour, data_qubit_that_links_them)]}``."""
    adj: dict[int, list[tuple[int, int]]] = {}
    for (a, b), data in edges.items():
        adj.setdefault(a, []).append((b, data))
        adj.setdefault(b, []).append((a, data))
    return adj


def shortest_paths(adj: dict[int, list[tuple[int, int]]],
                   source: int) -> dict[int, tuple[int, list[int]]]:
    """BFS shortest path from ``source`` to every reachable node.

    Unweighted: every syndrome-graph edge corresponds to one data-qubit error,
    so the number of edges is the number of corrections and is the right
    quantity to minimise.
    """
    dist: dict[int, tuple[int, list[int]]] = {source: (0, [])}
    queue = [source]
    while queue:
        node = queue.pop(0)
        d, path = dist[node]
        for neighbour, data in adj.get(node, []):
            if neighbour not in dist:
                dist[neighbour] = (d + 1, path + [data])
                queue.append(neighbour)
    return dist


def _perfect_matchings(nodes: tuple[int, ...]):
    """Every perfect matching of ``nodes``, which must have even length."""
    if not nodes:
        yield []
        return
    first, rest = nodes[0], nodes[1:]
    for index, partner in enumerate(rest):
        remaining = rest[:index] + rest[index + 1:]
        for tail in _perfect_matchings(remaining):
            yield [(first, partner), *tail]


class MWPMDecoder:
    """Minimum-weight perfect matching on the surface-code syndrome graph.

    **Exact for the instances it accepts.**  It enumerates perfect matchings
    rather than running Blossom, which is exponential in the number of detection
    events; ``max_events`` bounds that and the decoder *raises* rather than
    silently degrading to an approximation.

    Why this rather than PyMatching: PyMatching is excellent and is the right
    tool at scale, but adding it would take the package off its numpy-only
    promise for a decoder whose exact form is needed only on small syndromes.
    Where the instance is too large the honest outcome is a refusal.

    Why MWPM at all, given :func:`greedy_match` existed: greedy pairing is
    measurably worse, and a threshold is a property of the decoder as much as
    of the code. Pairing the wrong detection events produces a logical error
    rate that is too high, and the symptom is a threshold in the wrong place --
    a number that looks like physics and is an artifact.
    """

    def __init__(self, max_events: int = 16):
        if max_events < 2:
            raise SurfaceCodeError("max_events must be at least 2")
        self.max_events = max_events

    def decode(self, code: RotatedSurfaceCode, syndrome: set[int],
               kind: str) -> DecodeResult:
        """Correct one syndrome of one check type."""
        graph = matching_graph(code, kind)
        adj = _adjacency(graph["edges"])
        boundaries = sorted(graph["boundary_nodes"])

        events = sorted(n for n in syndrome if n in adj)
        orphaned = sorted(n for n in syndrome if n not in adj)
        if len(events) > self.max_events:
            raise SurfaceCodeError(
                f"{len(events)} detection events exceeds the exact-matching "
                f"limit of {self.max_events}; greedy_match is available for "
                f"larger instances"
            )
        if not events:
            return DecodeResult(corrections=[], residual=orphaned,
                                logical_flip=False)

        # Matching runs on the detection events plus every boundary node: that, rather
        # than deciding in advance which events go to the edge, is what makes the
        # problem well posed, since any event may pair with any event or any boundary.
        # Events plus boundaries must be even for a perfect matching to exist; when it
        # is odd exactly one event must terminate on the boundary, which is physics,
        # since a chain ending at the code edge leaves an odd number of events. So each
        # event is tried in turn as the terminating one and the cheapest wins.
        distances: dict[int, dict[int, tuple[int, list[int]]]] = {}
        for node in events + boundaries:
            distances[node] = shortest_paths(adj, node)
        for a in boundaries:
            for b in boundaries:
                if a != b:
                    # Boundary nodes of the same check type are connected at zero cost,
                    # so a chain may run along an edge for free.
                    distances[a][b] = (0, [])

        def best_for(pool: tuple[int, ...]) -> tuple[int, list[int]] | None:
            best: tuple[int, list[int]] | None = None
            for matching in _perfect_matchings(pool):
                cost = 0
                path_data: list[int] = []
                feasible = True
                for a, b in matching:
                    found = distances.get(a, {}).get(b)
                    if found is None:
                        feasible = False
                        break
                    cost += found[0]
                    path_data.extend(found[1])
                if feasible and (best is None or cost < best[0]):
                    best = (cost, path_data)
            return best

        base = tuple(events) + tuple(boundaries)
        if len(base) % 2 == 0:
            best = best_for(base)
        else:
            best = None
            for index in range(len(events)):
                forced = events[index]
                pool = tuple(e for i, e in enumerate(events) if i != index) \
                    + tuple(boundaries)
                # The forced event must reach *some* boundary.
                to_boundary = [(distances[forced][b][0], distances[forced][b][1])
                               for b in boundaries if b in distances[forced]]
                if not to_boundary:
                    continue
                extra_cost, extra_path = min(to_boundary, key=lambda t: t[0])
                candidate = best_for(pool)
                if candidate is None:
                    continue
                cost = candidate[0] + extra_cost
                path_data = candidate[1] + extra_path
                if best is None or cost < best[0]:
                    best = (cost, path_data)

        if best is None:
            return DecodeResult(corrections=[], residual=events + orphaned,
                                logical_flip=False)

        corrections = best[1]
        logical = set(logical_operator_for(code, kind))
        flips = len(logical & set(corrections)) % 2 == 1
        return DecodeResult(corrections=sorted(set(corrections)),
                            residual=orphaned,
                            logical_flip=flips)


def decode_mwpm(code: RotatedSurfaceCode, syndrome: set[int], kind: str,
                **kwargs) -> DecodeResult:
    """Convenience wrapper around :class:`MWPMDecoder`."""
    return MWPMDecoder(**kwargs).decode(code, syndrome, kind)


# Clustered decoding: scalable, and honest about being an approximation

class ClusteredDecoder:
    """Grow-then-route decoding: pair events by shortest path, boundaries allowed.

    Why this exists alongside the exact matcher: perfect-matching enumeration is
    factorial in the detection-event count, and a realistic syndrome at
    ``p = 0.1%`` on a distance-5 code has of order ten events per round.  An
    exact decoder is therefore unusable for the thing a logical error rate is
    actually measured from, and a decoder that cannot be run is not a decoder.

    The algorithm is the greedy half of Union-Find's spirit and is stated as what
    it is: events are taken one at a time and connected to their nearest
    remaining partner -- another event or the nearest boundary -- by the shortest
    path through the syndrome graph.  Every edge contributes exactly one
    data-qubit correction, so path length in edges is the right cost.

    **It is an approximation, and it is named.**  Greedy nearest-neighbour
    pairing is not minimum-weight, and the gap is why a threshold is always
    quoted with the decoder beside it.  On the instances small enough for the
    exact matcher, ``test_clustered_never_costs_more_than_exact`` measures the
    difference rather than assuming it away.
    """

    def __init__(self, boundary_penalty: float = 0.0):
        #: Added to every boundary match. Zero reproduces plain greedy; a small positive
        #: value biases toward pairing events with each other, the right prior when
        #: boundaries are shared between many events.
        self.boundary_penalty = float(boundary_penalty)

    def decode(self, code: RotatedSurfaceCode, syndrome: set[int],
               kind: str) -> DecodeResult:
        graph = matching_graph(code, kind)
        adj = _adjacency(graph["edges"])
        nodes: set[int] = set()
        for a, b in graph["edges"]:
            nodes.add(a)
            nodes.add(b)
        boundaries = tuple(sorted(graph["boundary_nodes"]))

        events = sorted(n for n in syndrome if n in nodes)
        orphaned = sorted(n for n in syndrome if n not in nodes)
        if not events:
            return DecodeResult(corrections=[], residual=orphaned,
                                logical_flip=False)

        # Shortest paths from each event, once.
        paths = {e: shortest_paths(adj, e) for e in events}

        remaining = list(events)
        corrections: set[int] = set()
        unmatched: list[int] = []
        while remaining:
            event = remaining.pop(0)
            best_cost: float | None = None
            best_path: list[int] | None = None
            best_partner: int | None = None

            for other in remaining:
                found = paths[event].get(other)
                if found is not None and (best_cost is None
                                          or found[0] < best_cost):
                    best_cost, best_path, best_partner = found[0], found[1], other

            boundary_best: tuple[float, list[int]] | None = None
            for bound in boundaries:
                found = paths[event].get(bound)
                if found is None:
                    continue
                cost = found[0] + self.boundary_penalty
                if boundary_best is None or cost < boundary_best[0]:
                    boundary_best = (cost, found[1])

            if best_cost is not None and (boundary_best is None
                                          or best_cost <= boundary_best[0]):
                corrections.update(best_path or [])
                if best_partner in remaining:
                    remaining.remove(best_partner)
            elif boundary_best is not None:
                corrections.update(boundary_best[1])
            else:
                unmatched.append(event)

        logical = set(logical_operator_for(code, kind))
        flips = len(logical & corrections) % 2 == 1
        return DecodeResult(corrections=sorted(corrections),
                            residual=orphaned + unmatched,
                            logical_flip=flips)


def decode_clustered(code: RotatedSurfaceCode, syndrome: set[int], kind: str,
                     **kwargs) -> DecodeResult:
    """Convenience wrapper around :class:`ClusteredDecoder`."""
    return ClusteredDecoder(**kwargs).decode(code, syndrome, kind)
